### ISSUE TITLE
iOS: createActivation error userInfo propagation

### ISSUE THREAD

**Issue by radekfrolik** [lime-company/powerauth-mobile-sdk#70]
When PowerAuthSDK.sharedInstance().createActivation returns error in callback, such NSError does not contain any data in userInfo dictionary, even when there should be some.

**Comment by petrdvorak** [comment]
The issue is caused by the fact the `userInfo` dictionary is not passed from the network layer error to high-level SDK error.

The original and not properly executed idea behind error handling was following:

- Networking layer (`PA2Client`) may produce error on communication with server. In some cases (namely, for "HTTP 400" errors), the error response body from the server may contain additional information about the error cause. This is already handled [here](https://github.com/lime-company/powerauth-mobile-sdk/blob/development/proj-xcode/Classes/networking/client/PA2Client.m#L47) - serialized [error response object](https://github.com/lime-company/powerauth-crypto/wiki/Standard-RESTful-API#error-handling) is passed in `userInfo` dictionary.
- High-level layer should have the information about this low-level error in it's user info, so that it is hidden from most programmers and available to those who might need it. We do not handle this in high-level SDK...

_Note: The problem is not present on Android, root exception with response object is passed to high-level exception._

_Note2: While we should fix it for all methods, practically, this is an issue only for custom activation endpoint, since it is the only endpoint that may return some rich additional information._

**Comment by radekfrolik** [comment]
Temporary fix done in fork repo, [here](https://github.com/radekfrolik/powerauth-mobile-sdk/blob/bbb6bdc233bb8b650f982271d76d21d50d3ae33f/proj-xcode/Classes/sdk/PowerAuthSDK.m#L579), seems to be working fine for me

**Comment by hvge** [comment]
I've create my own hotfix. Check #72 pull request for details.
